### ISSUE TITLE
Vertex Inputs/Attributes

### ISSUE THREAD

**Issue by Luracasmus** [IrisShaders/DocsPage#232]
[These](https://optifine.readthedocs.io/shaders_dev.html?h=attribute#attributes) are supported by both OptiFine and Iris, but Iris also adds an additional component `w` to `at_midBlock` when using `BLOCK_EMISSION_ATTRIBUTE`.

There are also undocumented inputs such as `Position` and `UV0` in composite passes, and the `iris_` inputs in gbuffers. Should they also be added here?

**Comment by ninjamike1211** [comment]
These sound like Iris internal stuff, which is not usable directly in shaders (Iris will throw an error if you try iirc). `BLOCK_EMISSION_ATTRIBUTE` has been added
